'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ApplicationExplorer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend ReadOnly Property AboutLabel() As String
            Get
                Return ResourceManager.GetString("AboutLabel", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ApplicationIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ApplicationIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property book_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CopyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CutHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit_UndoHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_UndoHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FillDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FillDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FillRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FillRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FindHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Working....
        '''</summary>
        Friend ReadOnly Property GenericBusyMessage() As String
            Get
                Return ResourceManager.GetString("GenericBusyMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initializing....
        '''</summary>
        Friend ReadOnly Property GenericInitializingMessage() As String
            Get
                Return ResourceManager.GetString("GenericInitializingMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready.
        '''</summary>
        Friend ReadOnly Property GenericReadyMessage() As String
            Get
                Return ResourceManager.GetString("GenericReadyMessage", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property GoLtr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoLtr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoRtl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoRtl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HTMLPage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HTMLPage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InsertPhotos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsertPhotos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITEM_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_ADD2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITEM_ADD2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_DELETE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITEM_DELETE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_DELETE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITEM_DELETE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_EDIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITEM_EDIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_EDIT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITEM_EDIT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PasteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current window does not allow popping out to the desktop..
        '''</summary>
        Friend ReadOnly Property PopoutDisallowMessage() As String
            Get
                Return ResourceManager.GetString("PopoutDisallowMessage", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh_Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh_Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshDocView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshDocViewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend ReadOnly Property VersionLabel() As String
            Get
                Return ResourceManager.GetString("VersionLabel", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property window_close_glyph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_close_glyph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window_htile_glyph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_htile_glyph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window_popout_glyph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_popout_glyph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window_tile_glyph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_tile_glyph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This window cannot be closed..
        '''</summary>
        Friend ReadOnly Property WindowCloseDisallowMessage() As String
            Get
                Return ResourceManager.GetString("WindowCloseDisallowMessage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
